from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Any


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name, str(default)).strip().lower()
    return value in {"1", "true", "yes", "y", "on"}


def _cookie_domains() -> tuple[str, ...]:
    raw = os.getenv(
        "COOKIE_EXPORT_DOMAINS",
        "douyin.com,iesdouyin.com,bytedance.com,amemv.com,snssdk.com",
    )
    return tuple(x.strip().lower() for x in raw.split(",") if x.strip())


def _domain_allowed(domain: str) -> bool:
    d = (domain or "").lower().lstrip(".")
    return any(d == x or d.endswith("." + x) for x in _cookie_domains())


def _netscape_bool(value: bool) -> str:
    return "TRUE" if value else "FALSE"


def _cookie_expiry(cookie: dict[str, Any]) -> int:
    exp = cookie.get("expires")
    try:
        exp_i = int(float(exp))
    except Exception:
        exp_i = 0
    # session cookie: 给 yt-dlp 一个可读值，实际有效性仍由平台决定。
    if exp_i <= 0:
        exp_i = int(time.time()) + 7 * 24 * 3600
    return exp_i


def write_netscape_cookie_file(cookies: list[dict[str, Any]], path: str | Path) -> dict[str, Any]:
    """Write Playwright/browser cookies to a Netscape cookies.txt file.

    只导出抖音相关域名，不保存无关站点 cookies。
    """
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    rows = ["# Netscape HTTP Cookie File", "# Generated by AI-VIDEO collector-local"]
    count = 0
    for c in cookies:
        domain = str(c.get("domain") or "").strip()
        name = str(c.get("name") or "").strip()
        value = str(c.get("value") or "")
        if not domain or not name or not _domain_allowed(domain):
            continue
        include_subdomains = domain.startswith(".")
        path_value = str(c.get("path") or "/")
        secure = bool(c.get("secure"))
        expiry = _cookie_expiry(c)
        rows.append("\t".join([
            domain,
            _netscape_bool(include_subdomains),
            path_value,
            _netscape_bool(secure),
            str(expiry),
            name,
            value,
        ]))
        count += 1
    target.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return {"path": str(target), "count": count, "ok": count > 0}


async def refresh_cookies_from_context(context: Any, *, force: bool = False) -> dict[str, Any]:
    """Export fresh cookies from the active Playwright persistent Chrome context.

    用 ECS 上已经登录过的 Chrome profile 自动生成 douyin_cookies.txt，避免人工反复维护。
    失败不阻断采集。
    """
    if not force and not _env_bool("AUTO_REFRESH_COOKIES", True):
        return {"ok": False, "skipped": True, "reason": "AUTO_REFRESH_COOKIES=false"}
    cookie_path = os.getenv("YT_DLP_COOKIES_PATH") or os.getenv("DOUYIN_COOKIES_PATH") or "douyin_cookies.txt"
    try:
        cookies = await context.cookies()
        result = write_netscape_cookie_file(cookies, cookie_path)
        if result.get("ok"):
            print(f"自动刷新 cookies 成功：{result['path']}，{result['count']} 条")
        else:
            print(f"自动刷新 cookies 完成但未找到抖音相关 cookies：{result['path']}")
        return result
    except Exception as exc:
        print(f"自动刷新 cookies 失败，不阻断采集：{type(exc).__name__}: {exc}")
        return {"ok": False, "error": str(exc), "path": cookie_path}
