from __future__ import annotations

import argparse
import asyncio
import json
import os
import shutil
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from playwright.async_api import async_playwright

COLLECTOR_ROOT = Path("/opt/ai-video-worker/collector-local")
PROFILE_ROOT = COLLECTOR_ROOT / "profiles"
COOKIE_ROOT = COLLECTOR_ROOT / "cookies"
AUTH_ROOT = Path("/opt/ai-video/storage/douyin_auth_v10_40_8_3")
PROFILE_STATE_ROOT = AUTH_ROOT / "profiles"
LOGIN_COOKIE_NAMES = {
    "sessionid",
    "sessionid_ss",
    "sid_guard",
    "uid_tt",
    "uid_tt_ss",
}
COOKIE_DOMAINS = (
    "douyin.com",
    "iesdouyin.com",
    "bytedance.com",
    "amemv.com",
    "snssdk.com",
)


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.replace(path)


def read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {}
    except Exception:
        return {}


def update_session(path: Path, **patch: Any) -> dict[str, Any]:
    value = read_json(path)
    value.update(patch)
    value["updated_at"] = time.time()
    atomic_json(path, value)
    return value


def domain_allowed(domain: str) -> bool:
    clean = str(domain or "").lower().lstrip(".")
    return any(clean == suffix or clean.endswith("." + suffix) for suffix in COOKIE_DOMAINS)


def write_netscape(cookies: list[dict[str, Any]], target: Path) -> int:
    target.parent.mkdir(parents=True, exist_ok=True)
    rows = ["# Netscape HTTP Cookie File", "# Generated by AI-VIDEO Douyin QR login bridge"]
    count = 0
    for cookie in cookies:
        domain = str(cookie.get("domain") or "").strip()
        name = str(cookie.get("name") or "").strip()
        value = str(cookie.get("value") or "")
        if not domain or not name or not domain_allowed(domain):
            continue
        try:
            expires = int(float(cookie.get("expires") or 0))
        except Exception:
            expires = 0
        if expires <= 0:
            expires = int(time.time()) + 7 * 86400
        rows.append("\t".join([
            domain,
            "TRUE" if domain.startswith(".") else "FALSE",
            str(cookie.get("path") or "/"),
            "TRUE" if cookie.get("secure") else "FALSE",
            str(expires),
            name,
            value,
        ]))
        count += 1
    target.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return count


def clear_stale_singletons(profile_dir: Path) -> None:
    for name in ("SingletonLock", "SingletonCookie", "SingletonSocket"):
        path = profile_dir / name
        try:
            if path.is_symlink() or path.exists():
                path.unlink()
        except Exception:
            pass


async def click_login(page: Any) -> None:
    candidates = [
        page.get_by_text("登录", exact=True),
        page.locator("button:has-text('登录')"),
        page.locator("[class*='login'] button"),
        page.locator("[class*='Login'] button"),
    ]
    for candidate in candidates:
        try:
            if await candidate.count() > 0:
                first = candidate.first
                if await first.is_visible(timeout=1000):
                    await first.click(timeout=3000)
                    await page.wait_for_timeout(1200)
                    return
        except Exception:
            continue


async def capture_qr(page: Any, target: Path) -> str:
    selectors = [
        "[class*='qrcode'] canvas",
        "[class*='qrCode'] canvas",
        "[class*='QRCode'] canvas",
        "[class*='login'] canvas",
        "img[src*='qrcode']",
        "img[src*='qr']",
        "[class*='qrcode'] img",
        "[class*='qrCode'] img",
        "[class*='login'] img",
    ]
    for selector in selectors:
        try:
            locator = page.locator(selector)
            count = min(await locator.count(), 8)
            for index in range(count):
                item = locator.nth(index)
                box = await item.bounding_box()
                if not box or box["width"] < 120 or box["height"] < 120:
                    continue
                await item.screenshot(path=str(target))
                return "qr_element"
        except Exception:
            continue
    await page.screenshot(path=str(target), full_page=False)
    return "full_login_page"


def has_login_cookie(cookies: list[dict[str, Any]]) -> bool:
    names = {str(cookie.get("name") or "") for cookie in cookies if domain_allowed(str(cookie.get("domain") or ""))}
    return bool(names & LOGIN_COOKIE_NAMES)


async def run(args: argparse.Namespace) -> int:
    session_path = Path(args.session_file)
    profile = args.account_profile
    profile_dir = PROFILE_ROOT / profile
    cookie_file = COOKIE_ROOT / f"{profile}.txt"
    qr_path = session_path.with_suffix(".png")
    profile_state_path = PROFILE_STATE_ROOT / f"{profile}.json"
    deadline = time.time() + int(args.timeout_seconds)

    profile_dir.mkdir(parents=True, exist_ok=True)
    COOKIE_ROOT.mkdir(parents=True, exist_ok=True)
    PROFILE_STATE_ROOT.mkdir(parents=True, exist_ok=True)
    clear_stale_singletons(profile_dir)

    update_session(
        session_path,
        status="opening_browser",
        message="正在打开抖音登录页",
        profile_path=str(profile_dir),
        cookie_path=str(cookie_file),
    )

    try:
        async with async_playwright() as playwright:
            executable_path = os.getenv("CHROMIUM_EXECUTABLE_PATH", "").strip()
            if not executable_path:
                for candidate in ("google-chrome", "google-chrome-stable", "chromium", "chromium-browser"):
                    found = shutil.which(candidate)
                    if found:
                        executable_path = found
                        break
            launch_options: dict[str, Any] = {
                "user_data_dir": str(profile_dir),
                "headless": True,
                "viewport": {"width": 1280, "height": 900},
                "locale": "zh-CN",
                "args": [
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-blink-features=AutomationControlled",
                ],
            }
            if executable_path:
                launch_options["executable_path"] = executable_path
            update_session(
                session_path,
                browser_executable=executable_path or "playwright-bundled-chromium",
            )
            context = await playwright.chromium.launch_persistent_context(**launch_options)
            page = context.pages[0] if context.pages else await context.new_page()
            await page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=90000)
            await page.wait_for_timeout(2500)

            initial_cookies = await context.cookies()
            if has_login_cookie(initial_cookies):
                cookie_count = write_netscape(initial_cookies, cookie_file)
                state = {
                    "account_profile": profile,
                    "login_ok": cookie_count > 0,
                    "logged_in_at": time.time(),
                    "logged_in_at_iso": now_iso(),
                    "cookie_count": cookie_count,
                    "cookie_path": str(cookie_file),
                    "profile_path": str(profile_dir),
                    "last_error": "",
                }
                atomic_json(profile_state_path, state)
                update_session(
                    session_path,
                    status="logged_in",
                    message="当前隔离账号已有有效登录态",
                    cookie_count=cookie_count,
                )
                await context.close()
                return 0

            await click_login(page)
            update_session(
                session_path,
                status="waiting_scan",
                message="请使用手机抖音扫描页面二维码",
            )

            last_capture = 0.0
            while time.time() < deadline:
                cookies = await context.cookies()
                if has_login_cookie(cookies):
                    cookie_count = write_netscape(cookies, cookie_file)
                    state = {
                        "account_profile": profile,
                        "login_ok": cookie_count > 0,
                        "logged_in_at": time.time(),
                        "logged_in_at_iso": now_iso(),
                        "cookie_count": cookie_count,
                        "cookie_path": str(cookie_file),
                        "profile_path": str(profile_dir),
                        "last_error": "",
                    }
                    atomic_json(profile_state_path, state)
                    update_session(
                        session_path,
                        status="logged_in",
                        message="扫码登录成功，账号 Cookie 已按隔离区保存",
                        cookie_count=cookie_count,
                    )
                    await context.close()
                    return 0

                if time.time() - last_capture >= 3.0:
                    mode = await capture_qr(page, qr_path)
                    update_session(
                        session_path,
                        status="waiting_scan",
                        message="请使用手机抖音扫码；二维码过期时页面会自动刷新截图",
                        screenshot_mode=mode,
                    )
                    last_capture = time.time()

                await page.wait_for_timeout(1800)

            update_session(
                session_path,
                status="timeout",
                message="二维码登录超时，请重新发起登录",
                error="login_timeout",
            )
            atomic_json(
                profile_state_path,
                {
                    "account_profile": profile,
                    "login_ok": False,
                    "last_error": "二维码登录超时",
                    "updated_at": time.time(),
                },
            )
            await context.close()
            return 2
    except Exception as exc:
        message = f"{type(exc).__name__}: {exc}"
        update_session(
            session_path,
            status="failed",
            message="抖音登录窗口启动失败",
            error=message,
        )
        atomic_json(
            profile_state_path,
            {
                "account_profile": profile,
                "login_ok": False,
                "last_error": message,
                "updated_at": time.time(),
            },
        )
        return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--session-file", required=True)
    parser.add_argument("--account-profile", required=True, choices=["company_main", "company_backup", "personal_test"])
    parser.add_argument("--timeout-seconds", type=int, default=360)
    args = parser.parse_args()
    return asyncio.run(run(args))


if __name__ == "__main__":
    raise SystemExit(main())
